title: ðŸ§­ The Path
author: Dipak Pulami Magar
email: dpm.it24800@domain.com
description: > # this means to ignore newlines until "twitter_username:"
    Welcome to my GitHub Pages site â€” a space where I document my learning journey in Data Science, Machine Learning, and AI. I share technical notes, tutorials, projects, and reflections on Dhamma and mindfulness, blending analytical curiosity with inner understanding.

meta_description: >
  Exploring Data Science, Machine Learning, and AI â€” with insights on Dhamma, mindfulness, and life. A blend of technical learning and inner reflection.

# social links
linkedin_username: dpm24800
github_username:  dpm24800
instagram_username: dpm.it24800
facebook_username: dpm.dh24800
# rss: rss
# dribbble_username: jekyll
# flickr_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com

baseurl: "/" # the subpath of your site, e.g. /blog # the-path
url: "https://dpm24800.github.io" # the base hostname & protocol for your site, e.g. http://example.com
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# timezone: Asia/Kathmandu

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
# theme: minima
theme: null # disabled here to customize 

plugins:
 - jekyll-seo-tag
 - jekyll-feed

# null:
#   nav_links:
#       - title: "Data Science and AI"
#         url: /dsai/
#       - title: "Dhamma"
#         url: /dhamma/
#       - title: "Reflections"
#         url: /reflections/
#       - title: "Misc."
#         url: /misc/
#       - title: "About"
#         url: /about/

# kramdown:
#   input: GFM
#   hard_wrap: false
#   syntax_highlighter: rouge
#   syntax_highlighter_opts:
#     block:
#       disable: true
#   parse_block_html: true
#   auto_id_stripping: true